export const GET_COUNTRIES_PAGE = 'GET_COUNTRIES_PAGE';
export const GET_COUNTRIES_DEFAULT = 'GET_COUNTRIES_DEFAULT';
export const CHANGE_FILTER = 'CHANGE_FILTER';
export const GET_DETAIL_COUNTRY = 'GET_DETAIL_COUNTRY';
export const DROP_DETAIL_COUNTRY = 'DROP_DETAIL_COUNTRY';
export const GET_ACTIVITIES = 'GET_ACTIVITIES';
export const GET_COUNTRY_FOR_NAME = 'GET_COUNTRY_FOR_NAME';
export const DROP_NAME_SEARCH = 'DROP_NAME_SEARCH';